# Rustfmt configuration for Transmutation (Based on Qdrant standards)

# Edition
edition = "2024"

# Import organization
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"


