# Cargo configuration for transmutation

[build]
# Link search paths for docling FFI
rustflags = []

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,$ORIGIN",
    "-L", "native=cpp/build",
    "-L", "native=docling-parse/build",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@loader_path",
    "-L", "native=cpp/build",
    "-L", "native=docling-parse/build",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-L", "native=cpp/build/Release",
    "-L", "native=docling-parse/build/Release",
]

# Feature flags
[alias]
build-ffi = "build --release --features 'pdf,cli,docling-ffi'"
test-ffi = "test --features 'pdf,docling-ffi'"

